/**
 * i18n configuration for TrendPulse.
 *
 * Locales listed here must have a corresponding `messages/<locale>.json` file.
 * When an admin adds a new city with an unsupported language via /admin/cities,
 * a new locale is appended here and its message file is generated by
 * `scripts/translate.ts` using DeepL.
 */

export const locales = ['en', 'es', 'fr', 'ja', 'ko', 'pt', 'da'] as const;

export type Locale = (typeof locales)[number];

export const defaultLocale: Locale = 'en';

export const localeNames: Record<Locale, string> = {
  en: 'English',
  es: 'Español',
  fr: 'Français',
  ja: '日本語',
  ko: '한국어',
  pt: 'Português',
  da: 'Dansk',
};

/**
 * Flag emoji or ISO country for display purposes in the language switcher.
 * Note: these are representative country codes, not definitive — e.g. English
 * uses the UK flag by convention.
 */
export const localeFlags: Record<Locale, string> = {
  en: '🇬🇧',
  es: '🇪🇸',
  fr: '🇫🇷',
  ja: '🇯🇵',
  ko: '🇰🇷',
  pt: '🇵🇹',
  da: '🇩🇰',
};

export function isLocale(value: string): value is Locale {
  return (locales as readonly string[]).includes(value);
}
